#!/usr/bin/env python3
"""criteria_sweep.py — the Document 8 narrowness sweep, generated not hand-composed.

Re-runnable against HEAD (PROMPT_D [D3] / PROMPT_H [H7.3]): rows come from the
machine; verdicts come from the adjudication ledger seeded in VERDICTS below and
are otherwise PENDING. A hand-composed table decays the way the slice-6 gate
block decayed; this one diffs.

Usage:  python docs/dev/criteria_sweep.py > docs/dev/CRITERIA_SWEEP.md
Stdlib only. No cargo, no database, no network.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOC8 = ROOT / "docs" / "08_phase_b_success_criteria.md"

# Adjudicated verdicts (witnessed in the round-2 ledger and/or ruled in
# docs/dev/PROMPT_G_RULINGS.md). Everything not listed: PENDING (cited) /
# UNWITNESSED (uncited, sections A-H) / DEFERRED (uncited, sections I-J).
VERDICTS = {
    "SC-D01": ("NARROWER", "arch half scans 2 crates by literal + 1 token; G2 widens to discovered crate list"),
    "SC-B04": ("NARROWER", "IPC scan covers godhead-store only; pub-mod half meets; G3 widens + orders the HTTP wall"),
    "SC-H06": ("NARROWER", "sweep = 3 tables x 1 pattern vs 26 tables x secrets::scan; refusal half meets; G4 widens"),
    "SC-C07": ("NARROWER", "3 of 8 entries wall-tested; log clause unsatisfiable at substrate (G6 narrows the criterion; reclassified wall/signature/pinned)"),
    "SC-E01": ("SPLIT", "shape half meets (E01a); the universal moves to minted SC-E05 per G5"),
    "SC-F06": ("HALF+ANNOTATED", "the G13 model: unmet half named in-test, pinned to the Ollama slice"),
    "SC-K04": ("NARROWER", "sovereign-judgment flip is shape-preserving corruption the re-lint cannot catch; G7 content-hash closes the class"),
    "SC-A05": ("NARROWER", "skew's persisted RefusalRecord carries VALIDATION_FAILED not SCHEMA_MISMATCH (G1 miscode, fix ordered)"),
    "SC-K03": ("NARROWER", "ephemeral error is SchemaMismatch (right); persisted record code is not (same G1 miscode)"),
    "SC-H05": ("NARROWER", "exhaustion witnessed on one guarded path; release_lease unguarded, bias surfaces identity-less (B3)"),
    "SC-G01": ("MEETS-AS-RULED", "lawful wall test per G1; the agent-side mount refusal is IX.3 labor-rule debt owed by the Dogma, pinned to slice 10"),
    "SC-N04": ("MEETS+CLAIMS-SEAM", "G6 formally assigns the SC-C07 'crossing the seam' entry to this criterion's observation-window test"),
}

UNIVERSAL_RE = re.compile(r"\b(every|all |any |no |none|never|nothing|regardless|across any)\b", re.I)
ARCH_RE = re.compile(r"\b(architectural|arch/|compile-time|property test|property:)\b", re.I)


def parse_criteria():
    text = DOC8.read_text(encoding="utf-8")
    out = []
    for m in re.finditer(r"^- \*\*(SC-[A-N]\d{2})\*\*\s*[—-]\s*(.+)$", text, re.M):
        cid, body = m.group(1), m.group(2).strip()
        body = re.sub(r"\*\*", "", body)
        quant = []
        if UNIVERSAL_RE.search(body):
            quant.append("universal")
        if ARCH_RE.search(body):
            quant.append("arch")
        out.append((cid, body, "+".join(quant) or "plain"))
    return out


def find_citations():
    cites = {}
    for path in sorted(ROOT.glob("crates/*/tests/*.rs")):
        rel = path.relative_to(ROOT).as_posix()
        current_fn = "?"
        for lineno, line in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
            fn = re.search(r"\bfn\s+([a-zA-Z0-9_]+)\s*\(", line)
            if fn:
                current_fn = fn.group(1)
            for cid in re.findall(r"SC-([A-N]\d{2})", line):
                cites.setdefault("SC-" + cid, []).append((current_fn, rel, lineno))
            for cid in re.findall(r"\bsc_([a-n]\d{2})", line):
                cites.setdefault("SC-" + cid.upper(), []).append((current_fn, rel, lineno))
    return cites


def main():
    criteria = parse_criteria()
    cites = find_citations()
    print("# CRITERIA SWEEP — Document 8 vs the test suite")
    print()
    print(f"Generated by `docs/dev/criteria_sweep.py` — re-run against HEAD; do not hand-edit.")
    print(f"Criteria found: {len(criteria)}. Verdicts: seeded from the round-2 adjudication")
    print("ledger + PROMPT_G_RULINGS; PENDING rows are the parallel, non-blocking sweep (S1).")
    print()
    print("| id | quantifier | citing test(s) | verdict | note |")
    print("|----|-----------|----------------|---------|------|")
    counts = {}
    for cid, body, quant in criteria:
        cs = cites.get(cid, [])
        seen, shown = set(), []
        for fn, rel, ln in cs:
            if fn not in seen:
                seen.add(fn)
                shown.append(f"`{fn}` {rel}:{ln}")
        cite_txt = "<br>".join(shown[:4]) + (f"<br>(+{len(shown)-4} more)" if len(shown) > 4 else "") if shown else "—"
        if cid in VERDICTS:
            verdict, note = VERDICTS[cid]
        elif not cs and cid[3] in "IJ":
            verdict, note = "DEFERRED", "section unbuilt; the one place the bookkeeping is clean (A8)"
        elif not cs:
            verdict, note = "UNWITNESSED", "no test cites this criterion"
        else:
            verdict, note = "PENDING", ""
        counts[verdict] = counts.get(verdict, 0) + 1
        print(f"| **{cid}** | {quant} | {cite_txt} | {verdict} | {note} |")
    print()
    print("## Tally")
    print()
    for v in sorted(counts):
        print(f"- {v}: {counts[v]}")
    print(f"- TOTAL: {sum(counts.values())}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
